name: 'SonarCloud GitHub Action (Wrapper)'
description: 'Wrapper composite action for SonarSource/sonarcloud-github-action. Update the version only here.'

inputs:
  args:
    description: 'Additional arguments to the Sonar Scanner CLI'
    required: false
    default: ''
  projectBaseDir:
    description: 'Set the sonar.projectBaseDir analysis property'
    required: false
    default: ''
  scannerVersion:
    description: 'Version of the Sonar Scanner CLI to use'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: ☁️ SonarCloud Scan
      id: sonar
      uses: SonarSource/sonarcloud-github-action@v5
      with:
        args: ${{ inputs.args }}
        projectBaseDir: ${{ inputs.projectBaseDir }}
        scannerVersion: ${{ inputs.scannerVersion }}
