# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

# timezone: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "America/Sao_Paulo"
    reviewers:
      - "felipementel"
    assignees:
      - "felipementel"
    labels:
      - "dependabot"
    commit-message:
      prefix: "[github actions] "

  - package-ecosystem: "github-actions"
    directories:
      - "/.github/actions/azure/aca-deploy"
      - "/.github/actions/azure/aca-naming"
      - "/.github/actions/azure/aca-summary"
      - "/.github/actions/dotnet/dotnet-test"
      - "/.github/actions/dotnet/get-version"
      - "/.github/actions/git/gist-badge"
      - "/.github/actions/git/tag-check"
      - "/.github/actions/git/tag-create"
      - "/.github/actions/node/env-values"
      - "/.github/actions/node/get-package-data"
      - "/.github/actions/python/code-quality"
      - "/.github/actions/python/get-version"
      - "/.github/actions/tools/code-quality/sonar-cloud-dotnet"
      - "/.github/actions/tools/code-quality/sonar-cloud-node"
      - "/.github/actions/tools/code-quality/sonar-cloud-python"
      - "/.github/actions/tools/code-quality/spectral"
      - "/.github/actions/tools/docker/buildx"
      - "/.github/actions/tools/docker/check-image"
      - "/.github/actions/tools/docker/install"
      - "/.github/actions/tools/docker/login"
      - "/.github/actions/tools/docker/push"
      - "/.github/actions/tools/docker/setup"
      - "/.github/actions/tools/security/checkov"
      - "/.github/actions/tools/security/giteaks"
      - "/.github/actions/tools/security/owasp-zap"
      - "/.github/actions/tools/security/safety-python"
      - "/.github/actions/tools/security/snyk-dotnet"
      - "/.github/actions/tools/security/trivy-scan"
      - "/.github/actions/_wrapper/github/upload-artifact"
      - "/.github/actions/_wrapper/github/cache"
      - "/.github/actions/_wrapper/github/setup-java"
      - "/.github/actions/_wrapper/github/setup-node"
      - "/.github/actions/_wrapper/docker/login-action"
      - "/.github/actions/_wrapper/docker/setup-qemu-action"
      - "/.github/actions/_wrapper/docker/setup-buildx-action"
      - "/.github/actions/_wrapper/docker/metadata-action"
      - "/.github/actions/_wrapper/docker/build-push-action"
      - "/.github/actions/_wrapper/sonar/sonarcloud-github-action"
      - "/.github/actions/_wrapper/github/checkout"
      - "/.github/actions/_wrapper/github/setup-dotnet"
      - "/.github/actions/_wrapper/codecov/codecov-action"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "America/Sao_Paulo"
    reviewers:
      - "felipementel"
    assignees:
      - "felipementel"
    labels:
      - "dependabot"
    commit-message:
      prefix: "[github actions composite] "
