# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

# timezone: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "America/Sao_Paulo"
    reviewers:
      - "felipementel"
    assignees:
      - "felipementel"
    labels:
      - "dependabot"
    commit-message:
      prefix: "[github actions] "

  - package-ecosystem: "github-actions"
    directory: "/.github/actions"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "America/Sao_Paulo"
    reviewers:
      - "felipementel"
    assignees:
      - "felipementel"
    labels:
      - "dependabot"
    commit-message:
      prefix: "[github actions] "
