name: 'Safety CLI Scan'
description: 'Runs Safety CLI to check Python dependencies for known vulnerabilities.'

inputs:
  api-key:
    description: 'Safety API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run Safety CLI to check for vulnerabilities
      uses: pyupio/safety-action@v1
      with:
        api-key: ${{ inputs.api-key }}
