name: 'Setup .NET Core SDK (Wrapper)'
description: 'Wrapper composite action for actions/setup-dotnet. Update the version only here.'

inputs:
  dotnet-version:
    description: 'Optional SDK version(s) to use. If not provided, will install global.json version when available.'
    required: false
  dotnet-quality:
    description: 'Optional quality of the build. Possible values: daily, signed, validated, preview, ga.'
    required: false
  global-json-file:
    description: 'Optional global.json location, if not located in the root of the repo.'
    required: false
  source-url:
    description: 'Optional package source for which to set up authentication.'
    required: false
  owner:
    description: 'Optional OWNER for using packages from GitHub Package Registry organizations/users.'
    required: false
  config-file:
    description: 'Optional NuGet.config location, if not located in the root of the repo.'
    required: false
  cache:
    description: 'Optional input to enable caching of the NuGet global-packages folder'
    required: false
    default: 'false'
  cache-dependency-path:
    description: 'Path to a dependency file: packages.lock.json. Supports wildcards or a list of file names.'
    required: false

outputs:
  cache-hit:
    description: 'A boolean value to indicate if a cache was hit.'
    value: ${{ steps.setup-dotnet.outputs.cache-hit }}
  dotnet-version:
    description: 'Contains the installed .NET SDK version.'
    value: ${{ steps.setup-dotnet.outputs.dotnet-version }}

runs:
  using: 'composite'
  steps:
    - name: 🛠️ Setup .NET
      id: setup-dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        dotnet-quality: ${{ inputs.dotnet-quality }}
        global-json-file: ${{ inputs.global-json-file }}
        source-url: ${{ inputs.source-url }}
        owner: ${{ inputs.owner }}
        config-file: ${{ inputs.config-file }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
