name: 'Snyk Security Scan'
description: 'Runs Snyk container monitor, vulnerability scan, uploads SARIF and artifacts.'

inputs:
  snyk-token:
    description: 'Snyk API token'
    required: true
  projectBaseDir:
    description: 'Path to project base directory'
    required: true
  mainProject:
    description: 'The main project name'
    required: true
  solutionFileName:
    description: 'The SLNX or SLN full name'
    required: true
  imageName:
    description: 'Image name for container scan'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 🍵 Restore dependencies
      shell: bash
      run: |
        dotnet restore \
          ${{ inputs.projectBaseDir }}/${{ inputs.mainProject }}/${{ inputs.mainProject }}.csproj
        dotnet build \
          ${{ inputs.projectBaseDir }}/${{ inputs.mainProject }}/${{ inputs.mainProject }}.csproj \
          --no-restore \
          --output ./output_build

    - name: 🍵 Snyk Setup
      uses: snyk/actions/setup@master

    - name: 🍵 Build a Docker image
      shell: bash
      run: |
        docker buildx build \
          -t felipementel/${{ inputs.imageName }} \
          -f ${{ inputs.projectBaseDir }}/${{ inputs.mainProject }}/Dockerfile \
          ${{ inputs.projectBaseDir }}

    - name: 🍵 Snyk Container Monitor
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
      run: |
        snyk container monitor felipementel/${{ inputs.imageName }} \
          --exclude-base-image-vulns \
          --file=${{ inputs.projectBaseDir }}/${{ inputs.mainProject }}/Dockerfile

    - name: 🍵 Run Snyk to check for vulnerabilities
      uses: snyk/actions/dotnet@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
      with:
        args: --sarif-file-output=snykDotNet.sarif --file=${{ inputs.projectBaseDir }}/${{ inputs.solutionFileName }}

    - name: 🍵📤 Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      continue-on-error: true
      with:
        sarif_file: snykDotNet.sarif

    - name: 🍵📤 Upload Snyk Container test
      uses: actions/upload-artifact@v4
      with:
        name: Snyk-Container-Test
        path: |
          vuln.json
