name: CI/CD Pipeline
run-name: "${{ github.actor }} - ${{ github.run_id }}"

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      buildMode:
        description: "Qual ação deseja fazer?"
        required: true
        default: 'Build'
        type: choice
        options:
          - Build
          - Build + Tag Validation

jobs:
  devsecops:
    name: DevSecOps Pipeline
    uses: felipementel/reusable-workflows/.github/workflows/examples/dotnet-sandbox-api.yml@main
    with:
      buildMode: ${{ github.event_name == 'workflow_dispatch' && inputs.buildMode || 'Build' }}
      environment: 'DEV'
      dotnetVersion: '9.x'
      projectBaseDir: ./src
      solutionFileName: 'DEPLOY.PROJECT.API.slnx'
      mainProject: 'DEPLOY.PROJECT.API'
      testsFolder: ''
      reportTitle: 'Canal DEPLOY'
      sonarExclusions: ''
      imageName: 'project-api'
      openAPIFolder: ''
      msgCanalDeploy: 'Canal DEPLOY - O melhor canal sobre .NET, Azure, DevOps e IA'
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
