name: Pull Request Check ⚡
run-name: "${{ github.actor }} - ${{ github.run_id }}"

#SECRETS: GITLEAKS_LICENSE, SONAR_TOKEN, SONAR_PROJECT_KEY, SNYK_TOKEN
#VARS: SONAR_ORGANIZATION

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment to run the workflow'
        required: true
        default: 'DEV'
      testsFolder:
        type: string
        description: 'The main test folder'
        required: false
        default: 'tests'
      msgCanalDeploy:
        type: string
        description: 'Message to be displayed in the summary'
        required: false
        default: 'Canal DEPLOY - O melhor canal sobre .NET, Azure, DevOps e IA'
      #build config
      dotnetVersion:
        type: string
        description: '.NET Version'
        required: true
        default: 9.x
      projectBaseDir:
        type: string
        description: 'Path to SLNX file'
        required: true
        default: ./src
      solutionFileName:
        type: string
        description: 'The SLNX full name. eg: DEPLOY.PROJECT.API.slnx'
        required: true
        default: ""
      mainProject:
        type: string
        description: 'The main project. eg: DEPLOY.PROJECT.API'
        required: true
        default: ""
      reportTitle:
        type: string
        description: 'Message to be displayed in the unit test report title'
        required: true
        default: 'Canal DEPLOY'
      #build use
      sonarExclusions:
        type: string
        description: 'Path to exclusion from sonar, like migrations. Use comma separation'
        required: true
        default: ""
      #push-image
      imageName:
        type: string
        description: 'Image name to publish at github packages'
        required: true
        default: ""
      openAPIFolder:
        type: string
        description: ''
        required: true
        default: ""

env:
  RED: '\033[0;31m'
  GREEN: '\033[0;32m'
  YELLOW: '\033[0;33m'
  BLUE: '\033[0;34m'
  RESET: '\033[0m'
  BOLD: '\033[1m'
  UNDERLINE: '\033[4m'
  BOLD_UNDERLINE: '\033[1;4m'
  BOLD_RED: '\033[1;31m'
  BOLD_GREEN: '\033[1;32m'
  BOLD_YELLOW: '\033[1;33m'
  BOLD_BLUE: '\033[1;34m'

  javaVersion: 23
  javaDistro: zulu
  nodeVersion: 22

jobs:
  build:
    name: Build
    environment: ${{ inputs.environment }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    outputs:
      tag-version: ${{ steps.get-version.outputs.TAG }}
      now: ${{ steps.get-env.outputs.NOW }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 🧭 Get Environment
        id: get-env
        run: |
          echo -e "${GREEN} ⚠️ Environment ${{ inputs.environment }}"
          echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: 📥 Checkout
        uses: felipementel/reusable-workflows/.github/actions/_wrapper/github/checkout@main
        with:
          ref: ${{ github.ref }}
          sparse-checkout: |
            src
            tests
          sparse-checkout-cone-mode: false

      - name: 🔍 Get-Version from csproj
        id: get-version
        uses: felipementel/gh-actions/.github/actions/dotnet/get-version@main
        with:
          projectBaseDir: ${{ inputs.projectBaseDir }}
          mainProject: ${{ inputs.mainProject }}

      - name: 🛠️ Setup .NET version ${{ inputs.dotnetVersion }}
        uses: felipementel/reusable-workflows/.github/actions/_wrapper/github/setup-dotnet@main
        with:
          dotnet-version: ${{ inputs.dotnetVersion }}

      - name: ✅ Check .NET version in use
        run: |
          echo "DOTNET_ROOT: $DOTNET_ROOT"
          $DOTNET_ROOT/dotnet --info

      - name: 🧪 Dotnet Test & Coverage
        id: dotnet-test
        uses: felipementel/gh-actions/.github/actions/dotnet/dotnet-test@main
        with:
          testsFolder: ${{ inputs.testsFolder }}
          reportTitle: ${{ inputs.reportTitle }}
          sonarExclusions: ${{ inputs.sonarExclusions }}
          run-number: ${{ github.run_number }}
          run-id: ${{ github.run_id }}

      - name: Event name
        run: |
          echo "${{ github.event_name }}"

      - name: 🧱📤 Git Leaks
        if: github.event_name != 'pull_request_target'
        uses: felipementel/gh-actions/.github/actions/tools/security/giteaks@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gitleaks-license: ${{ secrets.GITLEAKS_LICENSE }}

      - name: 🐋 Docker Install
        if: ${{ steps.dotnet-test.outputs.has-tests == 'true' }}
        uses: felipementel/gh-actions/.github/actions/tools/docker/install@main

      - name: 📸 SonarCloud Analysis
        uses: felipementel/gh-actions/.github/actions/tools/code-quality/sonar-cloud-dotnet@main
        with:
          has-tests: ${{ steps.dotnet-test.outputs.has-tests }}
          sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
          sonar-organization: ${{ vars.SONAR_ORGANIZATION }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-exclusions: ${{ inputs.sonarExclusions }}
          projectBaseDir: ${{ inputs.projectBaseDir }}
          mainProject: ${{ inputs.mainProject }}
          solutionFileName: ${{ inputs.solutionFileName }}
          java-version: ${{ env.javaVersion }}
          java-distro: ${{ env.javaDistro }}

      - name: 🐳 Docker Build (local, for Snyk scan)
        uses: felipementel/gh-actions/.github/actions/tools/docker/buildx@main
        with:
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          image-name: ${{ inputs.imageName }}
          tag-version: ${{ github.sha }}
          dockerfile: ${{ inputs.projectBaseDir }}/${{ inputs.mainProject }}/Dockerfile
          context: ${{ inputs.projectBaseDir }}
          push: 'false'

      - name: 🍵 Snyk Security Scan
        uses: felipementel/gh-actions/.github/actions/tools/security/snyk-dotnet@main
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}
          projectBaseDir: ${{ inputs.projectBaseDir }}
          mainProject: ${{ inputs.mainProject }}
          solutionFileName: ${{ inputs.solutionFileName }}
          imageName: ghcr.io/${{ github.actor }}/${{ inputs.imageName }}:${{ github.sha }}
          docker-file-full-path: ${{ inputs.projectBaseDir }}/${{ inputs.mainProject }}/Dockerfile
          docker-build-context: ${{ inputs.projectBaseDir }}

      - name: 🔨 Build to generate OpenAPI JSON
        if: ${{ inputs.openAPIFolder != '' }}
        shell: bash
        run: |
          dotnet restore \
            ${{ inputs.projectBaseDir }}/${{ inputs.mainProject }}/${{ inputs.mainProject }}.csproj
          dotnet build \
            ${{ inputs.projectBaseDir }}/${{ inputs.mainProject }}/${{ inputs.mainProject }}.csproj \
            --no-restore \
            --output ./output_build

      - name: 🎗️ Spectral OpenAPI Lint
        if: ${{ inputs.openAPIFolder != '' }}
        uses: felipementel/gh-actions/.github/actions/tools/code-quality/spectral@main
        with:
          openapi-files-path: ./output_build/${{ inputs.openAPIFolder }}
          node-version: ${{ env.nodeVersion }}
          projectBaseDir: ${{ inputs.projectBaseDir }}
          mainProject: ${{ inputs.mainProject }}
          needs-build: 'false'

      - name: 🧾 Write to workflow job summary
        run: |
          SUMMARY=$GITHUB_STEP_SUMMARY$'
          # Versão gerada\n
          | versao | data | 
          |--|--|
          | ${{ steps.get-version.outputs.tag }} | ${{ steps.get-env.outputs.now }} | \n
          Mensagem: ${{ inputs.msgCanalDeploy }}\n'
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

  check-image:
    name: Check if image exists
    runs-on: ubuntu-latest
    outputs:
      image-exists: ${{ steps.check-image-and-tag.outputs.IMAGE_EXISTS }}
    needs: build
    steps:
      - name: 🔍 Check if image exists in registry
        id: check-image-and-tag
        uses: felipementel/gh-actions/.github/actions/tools/docker/check-image@main
        with:
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: deploy.${{ inputs.imageName }}
          tag-version: ${{ needs.build.outputs.tag-version }}

  notify-image-not-exists:
    name: Notify when image not exists
    needs: [build, check-image]
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    if: ${{ needs.check-image.outputs.image-exists == 'false' }}
    steps:
      - name: 🧾 Write to workflow job summary
        run: |
          echo "Image with tag ${{ needs.build.outputs.tag-version }} can be deployed. Push image to registry and publish on Azure Cloud." >> $GITHUB_STEP_SUMMARY

  notify-image-exists:
    name: Notify when already image exists
    needs: [build, check-image]
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    if: ${{ needs.check-image.outputs.image-exists == 'true' }}
    steps:
      - name: 🧾 Write to workflow job summary
        run: |
          echo "Image with tag ${{ needs.build.outputs.tag-version }} already exists. Skipping push image to registry and publish on Azure Cloud." >> $GITHUB_STEP_SUMMARY
